---
title: "HW2"
author: "Abdul-Rashid Zakaria"
date: "2/8/2022"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Load libraries and data
library(dplyr)
library(caret)
library(corrplot)
library(ggplot2)
library(e1071)
library(Hmisc)
library(mlbench)
library(reshape2)
library(subselect)
library(vcd)
library(AppliedPredictiveModeling)
```





```{r}

#Sample code for plotting frequency pot




#Question 4.1b

#set seed for reproducibility

set.seed(25)

# Create unbalanced classes

n <- 12495

classes <- sample(c(12,24,30), n, replace = TRUE, prob = c(0.7,0.2,0.1))

# Print table of proportions of classes

print(table(classes))

# Split classes using createDataPartition function

training <- createDataPartition(classes, p = 0.7)

# Verify creation of stratified datasets

table_training <-  table(classes[training$Resample1])

print(table_training/sum(table_training))

# Sample code for Using k = 10 fold cross-validation on training set classes (train_classes)

#ten_foldCV <- createDataPartition(train_classes, k = 10, returnTrain = TRUE)

```

```{r}
#Question 4.3
set.seed(25)

#load data

data("ChemicalManufacturingProcess")
pls_method <- train(Yield ~ .,data = ChemicalManufacturingProcess, method = "pls", preProc = c("center", "scale"), tuneLength = 10, trControl = trainControl(method = "repeatedcv", repeats = 5))
```


```{r}
data(ChemicalManufacturingProcess)

save_plots = FALSE
set.seed(25)

# Get the given data into a form we can plot:
#
components <- 1:10
means <- c( 0.444, 0.500, 0.533, 0.545, 0.542, 0.537, 0.534, 0.534, 0.520, 0.507 )
std_errors <- c( 0.0272, 0.0298, 0.0302, 0.0308, 0.0322, 0.0327, 0.0333, 0.0330, 0.0326, 0.0324 )
data = data.frame( components, means, std_errors ) 

if(save_plots){postscript()}
errbar( components, means, means+std_errors, means-std_errors )  
grid()
max_index = which.max( means )
```

```{r}
optimal_value <- subset(data, components == which.max(data$means) )
data$tolerance <- (data$means - optimal_value$mean)/optimal_value$means * 100

#Plot tolerance against number of PLS components

qplot(components, tolerance, data = data)

```

